 
from pygamesimpleobject.object_class import NewObject
from pygamesimpleobject.tilemap import TileMap
from pygamesimpleobject.draw import DrawObjects

from pygamesimpleobject.object_collision import CollisionCheck,AddCollision,DelteCollision