 
from PygameSimpleObject.object_class import NewObject

from PygameSimpleObject.object_collision import CollisionCheck


from PygameSimpleObject.object_collision import CollisionCheck,AddCollision,DelteCollision